[platformio]
default_envs = tracker

[env:tracker]
platform   = espressif32
board      = esp32dev
framework  = arduino

upload_port   = COM9
monitor_port  = COM9
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib@^6.6.0
    mikalhart/TinyGPSPlus@^1.0.3
    adafruit/Adafruit NeoPixel@^1.12.3

build_flags =
    -DCORE_DEBUG_LEVEL=0

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

[env:tracker_ota]
extends = env:tracker
upload_protocol = espota
; Set to the tracker IP shown in boot logs when OTA mode is active.
upload_port = 192.168.0.201
